=== tkman904/2025-07-21-WebStudy/JSPBasicProject_3/src/main/webapp/xml/sawon.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
	 <sawon>
	   <list>
	     <sabun></sabun>
	     <name></name>
	     <dept></dept>
	     <phone></phone>
	     <address></address>
	   </list>
	   <list>
	     <sabun></sabun>
	     <name></name>
	     <dept></dept>
	     <tel></tel>
	     <address></address>
	   </list>
	 </sawon>
 -->
<!ELEMENT sawon (list+)>
<!ELEMENT list (sabun, name, dept, (phone|tel), address)>
<!ELEMENT sabun (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT dept (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT tel (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ENTITY nbsp " "> <!-- &nbsp; -->
<!ENTITY lt "<">
<!ENTITY gt ">">
<!ENTITY sawon "sawon.xml">

=== tkman904/2025-07-21-WebStudy/JSPBasicProject_3/src/main/webapp/xml/sawon.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sawon SYSTEM "sawon.dtd">
<sawon>
  <list>
    <sabun></sabun>
    <name></name>
    <dept></dept>
    <phone></phone>
    <address></address>
  </list>
  <list>
    <sabun></sabun>
    <name></name>
    <dept></dept>
    <tel></tel>
    <address></address>
  </list>
</sawon>
